api_platform:

    title: 'Api-QCM'
    description: 'API QCM'
    version: '0.1.0'

    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        yaml:     ['application/x-yaml']
        xml:      ['application/xml', 'text/xml']
        html:     ['text/html']

    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/api_platform/resources']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
